version: "3.3"

services:
  vsc-node: # name of the service
    build: .
    image: vsc-node # the image to use
    container_name: vsc-node_dev # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    #external_links:
      #- mongo
    depends_on:
      - ipfs
      - mongo
    networks:
      - vsc-node
    env_file:
      - .env
    ports:
      - 1338:1337
    environment:
      DEV: true
      IPFS_HOST: http://ipfs:5201
      MONGO_HOST: mongo:27017
    volumes:
      - node-modules-store:/home/github/app/node_modules
      - ./data/vsc-node:/root/.vsc-node
      - ./seed-backup.json:/root/.vsc-seed-backup.json
      - ./.git/refs/heads/main:/root/git_commit
      - ./src:/home/github/app/src

  mongo:
    container_name: mongo_vsc_dev
    image: mongo:4.4.18
    restart: always
    ports:
      - 127.0.0.1:27022:27017
    networks:
      - vsc-node
    volumes:
      - ./data/vsc-db:/data/db

  ipfs:
    container_name: ipfs-vsc_dev
    image: ipfs/kubo:v0.18.1
    restart: always
    command:
      - daemon
      - --enable-pubsub-experiment
      - --init-profile
      - server
    networks:
      - vsc-node
    ports:
      - "4002:4002"
      - "127.0.0.1:5201:5201"
    environment: 
      IPFS_PATH: /etc/ipfs
    volumes:
      - ./data/ipfs:/etc/ipfs

volumes:
  node-modules-store: {}
  mongodb: {}
      
networks:
  vsc-node:
    driver: bridge
